Repository middyjs/middy, pull requests merged in 2018-03, with the labels that each got.

#117 Add typescript definitions for built-in middlewares
  index.d.ts
  middlewares.d.ts
  package-lock.json
  package.json
Labels: help wanted, type-systems

#135 Include middleware type definition when creating releases
  package-lock.json
  package.json
Labels: enhancement, type-systems

#137 Fixed wrong path import
  middlewares.d.ts
  package-lock.json
  package.json
Labels: bug, type-systems

#139 Add httpPartialResponse options interface
  middlewares.d.ts
  package-lock.json
  package.json
Labels: enhancement, type-systems

#141 Add SSM middleware to main README document
  README.md
  README.md.hb
  package-lock.json
  package.json
Labels: documentation, enhancement

#144 Make httpHeaderNormalizer opts optional in type definitions
  middlewares.d.ts
  package-lock.json
  package.json
Labels: type-systems
