Repository middyjs/middy, pull requests merged in 2019-05, with the labels that each got.

#331 Support reviver parameter in for http-json-body-parser
  lerna.json
  package-lock.json
  package.json
  packages/cache/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/do-not-wait-for-empty-event-loop/package.json
  packages/error-logger/package-lock.json
  packages/error-logger/package.json
  packages/function-shield/package-lock.json
  packages/function-shield/package.json
  packages/http-content-negotiation/package-lock.json
  packages/http-content-negotiation/package.json
  packages/http-cors/package.json
  packages/http-error-handler/package-lock.json
  packages/http-error-handler/package.json
  packages/http-event-normalizer/package.json
  packages/http-header-normalizer/package.json
  packages/http-json-body-parser/README.md
  packages/http-json-body-parser/__tests__/index.js
  packages/http-json-body-parser/index.d.ts
  packages/http-json-body-parser/index.js
  packages/http-json-body-parser/package-lock.json
  packages/http-json-body-parser/package.json
  packages/http-partial-response/package-lock.json
  packages/http-partial-response/package.json
  packages/http-response-serializer/package-lock.json
  packages/http-response-serializer/package.json
  packages/http-security-header/package.json
  packages/http-urlencode-body-parser/package-lock.json
  packages/http-urlencode-body-parser/package.json
  packages/input-output-logger/package-lock.json
  packages/input-output-logger/package.json
  packages/s3-key-normalizer/package.json
  packages/secrets-manager/package-lock.json
  packages/secrets-manager/package.json
  packages/ssm/package-lock.json
  packages/ssm/package.json
  packages/validator/package-lock.json
  packages/validator/package.json
  packages/warmup/package.json
Labels: enhancement, middleware

#335 fix: content type request bug in http serializer
  lerna.json
  package-lock.json
  package.json
  packages/cache/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/do-not-wait-for-empty-event-loop/package.json
  packages/error-logger/package-lock.json
  packages/error-logger/package.json
  packages/function-shield/package-lock.json
  packages/function-shield/package.json
  packages/http-content-negotiation/package-lock.json
  packages/http-content-negotiation/package.json
  packages/http-cors/package.json
  packages/http-error-handler/package-lock.json
  packages/http-error-handler/package.json
  packages/http-event-normalizer/package.json
  packages/http-header-normalizer/package.json
  packages/http-json-body-parser/package-lock.json
  packages/http-json-body-parser/package.json
  packages/http-partial-response/package-lock.json
  packages/http-partial-response/package.json
  packages/http-response-serializer/__tests__/index.js
  packages/http-response-serializer/index.js
  packages/http-response-serializer/package-lock.json
  packages/http-response-serializer/package.json
  packages/http-security-header/package.json
  packages/http-urlencode-body-parser/package-lock.json
  packages/http-urlencode-body-parser/package.json
  packages/input-output-logger/package-lock.json
  packages/input-output-logger/package.json
  packages/s3-key-normalizer/package.json
  packages/secrets-manager/package-lock.json
  packages/secrets-manager/package.json
  packages/ssm/package-lock.json
  packages/ssm/package.json
  packages/validator/package-lock.json
  packages/validator/package.json
  packages/warmup/package.json
Labels: bug, enhancement

#337 fix: httpErrorHandler minification type checking
  docs/middlewares.md
  package-lock.json
  package.json
  src/middlewares/__tests__/httpErrorHandler.js
  src/middlewares/httpErrorHandler.js
Labels: bug, enhancement, middleware

#341 fix: httpErrorHandler minification type checking
  lerna.json
  package-lock.json
  package.json
  packages/cache/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/do-not-wait-for-empty-event-loop/package.json
  packages/error-logger/package-lock.json
  packages/error-logger/package.json
  packages/function-shield/package-lock.json
  packages/function-shield/package.json
  packages/http-content-negotiation/package-lock.json
  packages/http-content-negotiation/package.json
  packages/http-cors/package.json
  packages/http-error-handler/README.md
  packages/http-error-handler/__tests__/index.js
  packages/http-error-handler/index.js
  packages/http-error-handler/package-lock.json
  packages/http-error-handler/package.json
  packages/http-event-normalizer/package.json
  packages/http-header-normalizer/package.json
  packages/http-json-body-parser/package-lock.json
  packages/http-json-body-parser/package.json
  packages/http-partial-response/package-lock.json
  packages/http-partial-response/package.json
  packages/http-response-serializer/package-lock.json
  packages/http-response-serializer/package.json
  packages/http-security-header/package.json
  packages/http-urlencode-body-parser/package-lock.json
  packages/http-urlencode-body-parser/package.json
  packages/input-output-logger/package-lock.json
  packages/input-output-logger/package.json
  packages/s3-key-normalizer/package.json
  packages/secrets-manager/package-lock.json
  packages/secrets-manager/package.json
  packages/ssm/package-lock.json
  packages/ssm/package.json
  packages/validator/package-lock.json
  packages/validator/package.json
  packages/warmup/package.json
Labels: enhancement, middleware
