Repository middyjs/middy, pull requests merged in 2019-06, with the labels that each got.

#342 Fix typo in the appetizer in README.md
  README.md
  README.md.hb
  package-lock.json
  package.json
Labels: documentation

#345 Update warmup.js to work alongside with doNotWaitForEmptyEventLoop
  docs/middlewares.md
  middlewares.d.ts
  package-lock.json
  package.json
  src/middlewares/__tests__/warmup.js
  src/middlewares/warmup.js
Labels: bug, enhancement, middleware

#354 Port waitForEmptyEventLoop in Warmup middlware (#345) to v.1.0.0 branch
  lerna.json
  package.json
  packages/cache/package.json
  packages/core/package.json
  packages/do-not-wait-for-empty-event-loop/package.json
  packages/error-logger/package.json
  packages/function-shield/package.json
  packages/http-content-negotiation/package.json
  packages/http-cors/package.json
  packages/http-error-handler/package.json
  packages/http-event-normalizer/package.json
  packages/http-header-normalizer/package.json
  packages/http-json-body-parser/package.json
  packages/http-partial-response/package.json
  packages/http-response-serializer/package.json
  packages/http-security-header/package.json
  packages/http-urlencode-body-parser/package.json
  packages/input-output-logger/package.json
  packages/s3-key-normalizer/package.json
  packages/secrets-manager/package.json
  packages/ssm/package.json
  packages/validator/package.json
  packages/warmup/README.md
  packages/warmup/__tests__/index.js
  packages/warmup/index.d.ts
  packages/warmup/index.js
  packages/warmup/package.json
Labels: feature request

#352 Add middy-env to 3rd party middleware list
  README.md
  README.md.hb
  package-lock.json
  package.json
Labels: documentation
